### PR TITLE
fix enchanted items exception

### PR DESCRIPTION
**Pull request by tvoklov**
Hi! I got a crash while using your mod.

Here's the trace:
```
java.lang.NoSuchMethodError: 'int net.minecraft.class_9304.method_57536(net.minecraft.class_1887)'
	at com.nettakrim.fishing_ruler.FishingRulerClient.update(FishingRulerClient.java:78)
	at com.nettakrim.fishing_ruler.FishingRulerClient.lambda$onInitializeClient$0(FishingRulerClient.java:43)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zgc000$fabric-lifecycle-events-v1$onEndTick(class_310.java:5183)
	at net.minecraft.class_310.method_1574(class_310.java:2012)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
```

I thought just wrapping the line throwing that in a try/catch should suffice, so I did that.
I will test later, but I don't think any further issues can appear because of this change.

### CODE REVIEW

**Comment by tvoklov** [comment]
unsure if it's a 1.21 thing, but whenever I fished out enchanted items, it would crash my game. tested this incredibly complicated fix, and now the crashes are gone.

not losing anything here, since chants will still print if they can, but now if they can't be printed at least the game won't crash.

**Comment by Nettakrim** [comment]
the whole item display is pretty buggy anyway, it already doesnt display all the time lol, so that fix is reasonable

**Comment by Nettakrim** [comment]
NoSuchMethodError does suggest the method changed in 1.21, and i guess because it doesnt immedietly crash i didnt notice lmao

**Comment by tvoklov** [comment]
so, are you gonna merge this?

**Comment by Nettakrim** [comment]
yeah ive just been distracted doing other things lol

**Pull request merged**
